package com.github.skarllot.android.skllib;

// Authors:
//  Fabrício Godoy <skarllot@gmail.com>, 2015.

/**
 * Represents an event data that carries a single data.
 */
public class SimpleEventData<T> extends EventData {
    private final T data;

    /**
     * Creates a new instance of SimpleEventData.
     *
     * @param data The data generated by current event.
     */
    public SimpleEventData(T data) {
        this.data = data;
    }

    /**
     * Gets the data keep by this event.
     *
     * @return The data.
     */
    public T getData() {
        return data;
    }
}
